name: aur-publish

on:
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: i3-auto-layout
            pkgbuild: PKGBUILD
          - name: i3-auto-layout-bin
            pkgbuild: PKGBUILD-bin

    steps:
    - name: Debug workflow run context
      run: |
        echo "Workflow Run Head Branch: ${{ github.event.workflow_run.head_branch }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
